name: Deploy
on:
  workflow_run:
    workflows: ["qa"]
    branches: [main]
    types:
      - completed
jobs:
  deploy:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: true
    steps:
      - uses: actions/checkout@v6
      - uses: moonrepo/setup-toolchain@v0
        with:
          auto-install: true
      - name: Install dependencies
        working-directory: ./web
        run: pnpm install --frozen-lockfile --strict-peer-dependencies
      - name: Build
        working-directory: ./web
        run: pnpm run build
        env:
          VITE_CONTENTFUL_SPACE_ID: ${{ secrets.REACT_APP_CONTENTFUL_SPACE_ID }}
          VITE_CONTENTFUL_ACCESS_TOKEN: ${{ secrets.REACT_APP_CONTENTFUL_ACCESS_TOKEN }}
          VITE_SENTRY_DSN: ${{ secrets.REACT_APP_SENTRY_DSN }}
          VITE_SENTRY_RELEASE: ${{ secrets.REACT_APP_SENTRY_RELEASE }}
      - name: Deploy
        working-directory: ./web
        run: pnpm run deploy
        env:
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
