name: qa
on:
  push:
    branches:
      - main
    paths:
      - "web/**"
      - ".github/workflows/**"
  pull_request:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v3
        with:
          version: "9.x"
      - uses: actions/setup-node@v4
        with:
          node-version: "20.x"
          registry-url: "https://registry.npmjs.org"
          cache: "pnpm"
          cache-dependency-path: "./web/pnpm-lock.yaml"
      - name: Install dependencies
        working-directory: ./web
        run: pnpm install --frozen-lockfile --strict-peer-dependencies
      - name: Run QA
        working-directory: ./web
        run: pnpm run qa
