[[headers]]
  for = "/service-worker.js"
  [headers.values]
  cache-control = '''
  max-age=0,
  no-cache,
  no-store,
  must-revalidate'''

[[redirects]]
  from = "https://gurutzeta.info/*"
  to = "https://app.gurutzeta.info/:splat"
  status = 301
  force = true

[[redirects]]
  from = "https://www.gurutzeta.info/*"
  to = "https://app.gurutzeta.info/:splat"
  status = 301
  force = true
